#' Plot Model Accuracy
#'
#' @param accuracy_data data generated by mcguiR::accuracy()
#' @param y desired value to be plotted - could be "correct", "incorrect", or "both"
#'
#' @return a plot of accuracy at each probability threshold
#' @export
#'
#' @examples
acc_plot <- function(accuracy_data, y = "correct") {
    if(y == "correct") {
        ggplot2::ggplot(data = accuracy_data, ggplot2::aes(x = threshold)) +
            ggplot2::geom_line(aes(y = correct, color = "#66C2A5")) +
            ggplot2::theme(legend.position = "none") +
            ggplot2::xlab("Probability Threshold") +
            ggplot2::ylab("Percent Correct (%)") +
            ggplot2::labs(title = "Accuracy at Different Probability Thresholds")
    }
    if(y == "incorrect") {
        ggplot2::ggplot(data = accuracy_data, ggplot2::aes(x = threshold)) +
            ggplot2::geom_line(aes(y = incorrect, color = "#D53E4F")) +
            ggplot2::theme(legend.position = "none") +
            ggplot2::xlab("Probability Threshold") +
            ggplot2::ylab("Percent Incorrect (%)") +
            ggplot2::labs(title = "Accuracy at Different Probability Thresholds")
    }
    if(y == "both") {
        ggplot2::ggplot(data = accuracy_data, ggplot2::aes(x = threshold)) +
            ggplot2::geom_line(aes(y = correct, color = "#66C2A5")) +
            ggplot2::geom_line(aes(y = incorrect, color = "#D53E4F")) +
            ggplot2::theme(legend.position = "none") +
            ggplot2::xlab("Probability Threshold") +
            ggplot2::ylab("Percent (%)") +
            ggplot2::labs(title = "Accuracy at Different Probability Thresholds")
    }
}
