#' Wrapper for DescTools::AUC
#'
#' @param ROC_value data frame generated by mcguiR::ROC_values()
#'
#' @return numeric value
#' @export
#'
#' @examples
#' \dontrun{
#' iris2 <- iris[stringr::str_detect(Species, "setosa", negate = T), ]
#' irismodel <- glm(Species ~ ., data = iris2, family = binomial)
#' roc_values <- ROC_value(irismodel, iris2, iris2$Species, "virginica", "versicolor")
#' AUC_wrapped(roc_values)}
AUC_wrapper <- function(ROC_value) {
    DescTools::AUC(x = ROC_value$FPR, y = ROC_value$TPR)
}
