#' Wrapper for DescTools::AUC
#'
#' @param ROC_values data frame generated by mcguiR::ROC_values()
#'
#' @return numeric value
#' @export
#'
#' @examples
AUC_wrapper <- function(ROC_values) {
    DescTools::AUC(x = ROC_values$FPR, y = ROC_values$TPR)
}
